name: Update README with GitHub Stats

on:
  schedule:
    - cron: "0 */6 * * *" # Executa a cada 6 horas
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Generate GitHub Stats
        run: |
          # Remove estatísticas antigas do README.md
          sed -i '/!\[GitHub Stats\]/d' README.md
          sed -i '/!\[Most Used Languages\]/d' README.md

          # Adiciona estatísticas atualizadas
          echo -e "\n![GitHub Stats](https://github-readme-stats.vercel.app/api?username=ednandias&show_icons=true&theme=radical)" >> README.md
          echo -e "\n![Most Used Languages](https://github-readme-stats.vercel.app/api/top-langs/?username=ednandias&layout=compact&theme=radical)" >> README.md

      - name: Commit and Push Changes (if needed)
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

          # Verifica se há mudanças antes de fazer commit
          if [[ `git status --porcelain` ]]; then
            git add README.md
            git commit -m "Update README with GitHub Stats and Most Used Languages"
            git push
          else
            echo "Sem mudanças para commitar."
          fi
